// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://neqkxwfvxwusrtzexmgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lcWt4d2Z2eHd1c3J0emV4bWdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExMjk2NjgsImV4cCI6MjA3NjcwNTY2OH0.2YDCP-Zs_pnhYbHNckscSv9N0N0P3ifpuESa_0xPsdc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});